using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.Intake;

public class IntakeSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public IntakeSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "IntakeLeads"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" VARCHAR(120) NOT NULL,
    "Email" VARCHAR(256) NULL,
    "PhoneNumber" VARCHAR(32) NULL,
    "NationalId" VARCHAR(32) NULL,
    "Subject" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NULL,
    "DesiredCaseType" VARCHAR(80) NULL,
    "Status" VARCHAR(32) NOT NULL DEFAULT 'New',
    "QualificationNotes" VARCHAR(1024) NULL,
    "ConflictChecked" boolean NOT NULL DEFAULT false,
    "HasConflict" boolean NOT NULL DEFAULT false,
    "ConflictDetails" VARCHAR(1024) NULL,
    "AssignedEmployeeId" integer NULL,
    "NextFollowUpAt" timestamp without time zone NULL,
    "AssignedAt" timestamp without time zone NULL,
    "ConvertedCustomerId" integer NULL,
    "ConvertedCaseCode" integer NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "IntakeLeads" ADD COLUMN IF NOT EXISTS "AssignedEmployeeId" integer NULL;
ALTER TABLE "IntakeLeads" ADD COLUMN IF NOT EXISTS "NextFollowUpAt" timestamp without time zone NULL;
ALTER TABLE "IntakeLeads" ADD COLUMN IF NOT EXISTS "AssignedAt" timestamp without time zone NULL;

CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_Status_CreatedAt" ON "IntakeLeads"("Status", "CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_Email" ON "IntakeLeads"("Email");
CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_PhoneNumber" ON "IntakeLeads"("PhoneNumber");
CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_FirmId" ON "IntakeLeads"("FirmId");
CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_AssignedEmployeeId" ON "IntakeLeads"("AssignedEmployeeId");
CREATE INDEX IF NOT EXISTS "IX_IntakeLeads_NextFollowUpAt" ON "IntakeLeads"("NextFollowUpAt");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("Intake schema ensured");
    }
}
