// Mocks generated by Mockito — do not edit by hand.
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: subtype_of_sealed_class, invalid_use_of_internal_member
// ignore_for_file: unnecessary_parenthesis, prefer_const_constructors

import 'package:mockito/mockito.dart';

import 'package:qadaya_lawyersys/core/auth/biometric_auth.dart';
import 'package:qadaya_lawyersys/core/storage/secure_storage.dart';
import 'package:qadaya_lawyersys/features/authentication/models/login_request.dart';
import 'package:qadaya_lawyersys/features/authentication/models/user_session.dart';
import 'package:qadaya_lawyersys/features/authentication/repositories/auth_repository.dart';

// ── MockAuthRepository ────────────────────────────────────────────────────────

class MockAuthRepository extends Mock implements AuthRepository {
  @override
  Future<UserSession> login(LoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(#login, [request]),
        returnValue: Future<UserSession>.value(_dummySession()),
        returnValueForMissingStub: Future<UserSession>.value(_dummySession()),
      ) as Future<UserSession>);

  @override
  Future<UserSession?> getStoredSession() =>
      (super.noSuchMethod(
        Invocation.method(#getStoredSession, []),
        returnValue: Future<UserSession?>.value(null),
        returnValueForMissingStub: Future<UserSession?>.value(null),
      ) as Future<UserSession?>);

  @override
  Future<bool> setBiometricEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(#setBiometricEnabled, [enabled]),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);

  @override
  Future<void> registerDeviceToken(String? deviceToken, {String? platform}) =>
      (super.noSuchMethod(
        Invocation.method(#registerDeviceToken, [deviceToken],
            {#platform: platform}),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<void> logout() =>
      (super.noSuchMethod(
        Invocation.method(#logout, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);
}

// ── MockBiometricAuthService ──────────────────────────────────────────────────

class MockBiometricAuthService extends Mock implements BiometricAuthService {
  @override
  Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
        Invocation.method(#isBiometricAvailable, []),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);

  @override
  Future<bool> authenticate() =>
      (super.noSuchMethod(
        Invocation.method(#authenticate, []),
        returnValue: Future<bool>.value(false),
        returnValueForMissingStub: Future<bool>.value(false),
      ) as Future<bool>);
}

// ── MockSecureStorage ─────────────────────────────────────────────────────────

class MockSecureStorage extends Mock implements SecureStorage {
  @override
  Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
        Invocation.method(#write, [key, value]),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<String?> read(String? key) =>
      (super.noSuchMethod(
        Invocation.method(#read, [key]),
        returnValue: Future<String?>.value(null),
        returnValueForMissingStub: Future<String?>.value(null),
      ) as Future<String?>);

  @override
  Future<void> delete(String? key) =>
      (super.noSuchMethod(
        Invocation.method(#delete, [key]),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<void> clear() =>
      (super.noSuchMethod(
        Invocation.method(#clear, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

UserSession _dummySession() => UserSession(
      userId: '',
      email: '',
      fullName: '',
      tenantId: '',
      tenantName: '',
      accessToken: '',
      refreshToken: '',
      tokenExpiresAt: DateTime.now(),
      roles: [],
      permissions: [],
      languageCode: 'en',
      biometricEnabled: false,
    );
