using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.CaseConversation;

public class CaseConversationSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public CaseConversationSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "CaseConversationMessages"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseCode" integer NOT NULL,
    "SenderUserId" VARCHAR(256) NOT NULL DEFAULT '',
    "SenderName" VARCHAR(256) NOT NULL DEFAULT '',
    "SenderRole" VARCHAR(64) NOT NULL DEFAULT '',
    "Message" VARCHAR(4000) NOT NULL,
    "VisibleToCustomer" boolean NOT NULL DEFAULT TRUE,
    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "CaseCode" integer NOT NULL DEFAULT 0;
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "SenderUserId" VARCHAR(256) NOT NULL DEFAULT '';
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "SenderName" VARCHAR(256) NOT NULL DEFAULT '';
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "SenderRole" VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "Message" VARCHAR(4000) NOT NULL DEFAULT '';
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "VisibleToCustomer" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "FirmId" integer NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS "IX_CaseConversationMessages_CaseCode_CreatedAtUtc" ON "CaseConversationMessages"("CaseCode", "CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_CaseConversationMessages_FirmId" ON "CaseConversationMessages"("FirmId");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("Case conversation schema ensured");
    }
}
