using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.Auditing;

public class AuditLogSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public AuditLogSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "AuditLogs"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityName" VARCHAR(128) NOT NULL,
    "Action" VARCHAR(16) NOT NULL,
    "EntityId" VARCHAR(256) NULL,
    "OldValues" TEXT NULL,
    "NewValues" TEXT NULL,
    "UserId" VARCHAR(256) NULL,
    "UserName" VARCHAR(256) NULL,
    "Timestamp" TIMESTAMP NOT NULL,
    "RequestPath" VARCHAR(512) NULL
);

CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp" ON "AuditLogs"("Timestamp" DESC);
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_EntityName" ON "AuditLogs"("EntityName");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("AuditLogs table schema ensured");
    }
}
