using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.TrustAccounting;

public class TrustAccountingSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public TrustAccountingSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        var providerName = _context.Database.ProviderName ?? string.Empty;
        if (providerName.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
        {
            await EnsurePostgresAsync(cancellationToken);
        }
        else
        {
            await EnsureSqlServerAsync(cancellationToken);
        }

        Log.Information("Trust accounting schema ensured");
    }

    private Task EnsureSqlServerAsync(CancellationToken cancellationToken)
    {
        const string sql = """
IF OBJECT_ID(N'dbo.TrustLedgerEntries', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TrustLedgerEntries
    (
        Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CustomerId INT NOT NULL,
        CaseCode INT NULL,
        EntryType NVARCHAR(32) NOT NULL,
        Amount FLOAT NOT NULL,
        OperationDate DATE NOT NULL,
        Description NVARCHAR(1024) NULL,
        Reference NVARCHAR(128) NULL,
        CreatedAt DATETIME2 NOT NULL,
        CreatedBy NVARCHAR(256) NULL,
        FirmId INT NOT NULL CONSTRAINT DF_TrustLedgerEntries_FirmId DEFAULT(1),
        CONSTRAINT CK_TrustLedgerEntries_Amount_Positive CHECK (Amount > 0),
        CONSTRAINT FK_TrustLedgerEntries_Customers FOREIGN KEY (CustomerId) REFERENCES dbo.Customers(Id) ON DELETE CASCADE,
        CONSTRAINT FK_TrustLedgerEntries_Cases FOREIGN KEY (CaseCode) REFERENCES dbo.Cases(Code) ON DELETE SET NULL
    );

    CREATE INDEX IX_TrustLedgerEntries_FirmId ON dbo.TrustLedgerEntries(FirmId);
    CREATE INDEX IX_TrustLedgerEntries_CustomerId_OperationDate ON dbo.TrustLedgerEntries(CustomerId, OperationDate, Id);
END

IF OBJECT_ID(N'dbo.TrustReconciliations', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TrustReconciliations
    (
        Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ReconciliationDate DATE NOT NULL,
        BankStatementBalance FLOAT NOT NULL,
        BookBalance FLOAT NOT NULL,
        ClientLedgerBalance FLOAT NOT NULL,
        BankToBookDifference FLOAT NOT NULL,
        ClientToBookDifference FLOAT NOT NULL,
        Notes NVARCHAR(1024) NULL,
        CreatedAt DATETIME2 NOT NULL,
        CreatedBy NVARCHAR(256) NULL,
        FirmId INT NOT NULL CONSTRAINT DF_TrustReconciliations_FirmId DEFAULT(1)
    );

    CREATE INDEX IX_TrustReconciliations_FirmId ON dbo.TrustReconciliations(FirmId);
    CREATE INDEX IX_TrustReconciliations_ReconciliationDate ON dbo.TrustReconciliations(ReconciliationDate DESC);
END
""";

        return _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }

    private Task EnsurePostgresAsync(CancellationToken cancellationToken)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "TrustLedgerEntries"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" integer NOT NULL,
    "CaseCode" integer NULL,
    "EntryType" character varying(32) NOT NULL,
    "Amount" double precision NOT NULL,
    "OperationDate" date NOT NULL,
    "Description" character varying(1024) NULL,
    "Reference" character varying(128) NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(256) NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "CK_TrustLedgerEntries_Amount_Positive" CHECK ("Amount" > 0),
    CONSTRAINT "FK_TrustLedgerEntries_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TrustLedgerEntries_Cases" FOREIGN KEY ("CaseCode") REFERENCES "Cases" ("Code") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_TrustLedgerEntries_FirmId" ON "TrustLedgerEntries" ("FirmId");
CREATE INDEX IF NOT EXISTS "IX_TrustLedgerEntries_CustomerId_OperationDate" ON "TrustLedgerEntries" ("CustomerId", "OperationDate", "Id");

CREATE TABLE IF NOT EXISTS "TrustReconciliations"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReconciliationDate" date NOT NULL,
    "BankStatementBalance" double precision NOT NULL,
    "BookBalance" double precision NOT NULL,
    "ClientLedgerBalance" double precision NOT NULL,
    "BankToBookDifference" double precision NOT NULL,
    "ClientToBookDifference" double precision NOT NULL,
    "Notes" character varying(1024) NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(256) NULL,
    "FirmId" integer NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS "IX_TrustReconciliations_FirmId" ON "TrustReconciliations" ("FirmId");
CREATE INDEX IF NOT EXISTS "IX_TrustReconciliations_ReconciliationDate" ON "TrustReconciliations" ("ReconciliationDate" DESC);
""";

        return _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
    }
}
