// <auto-generated />
using System;
using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LawyerSys.Data.Migrations.Legacy
{
    [DbContext(typeof(LegacyDbContext))]
    partial class LegacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Case", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Invition_Date")
                        .HasColumnType("date");

                    b.Property<string>("Invition_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Invitions_Statment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Total_Amount")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK_Cases_1");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Users_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("Users_Id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Users_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Path")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("type")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phon_Number")
                        .HasColumnType("int");

                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Customers")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Employees")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
