using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.CaseCourtHistory;

public class CaseCourtHistorySchemaInitializer
{
    private readonly LegacyDbContext _context;

    public CaseCourtHistorySchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "CaseCourtHistory"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Case_Id" integer NOT NULL,
    "OldCourt_Id" integer NULL,
    "NewCourt_Id" integer NULL,
    "OldCourt_Name" VARCHAR(100) NULL,
    "NewCourt_Name" VARCHAR(100) NULL,
    "ChangeType" VARCHAR(24) NOT NULL DEFAULT 'Changed',
    "ChangedBy" VARCHAR(256) NULL,
    "ChangedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "Case_Id" integer NOT NULL DEFAULT 0;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "OldCourt_Id" integer NULL;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "NewCourt_Id" integer NULL;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "OldCourt_Name" VARCHAR(100) NULL;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "NewCourt_Name" VARCHAR(100) NULL;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "ChangeType" VARCHAR(24) NOT NULL DEFAULT 'Changed';
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "ChangedBy" VARCHAR(256) NULL;
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "ChangedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "CaseCourtHistory" ADD COLUMN IF NOT EXISTS "FirmId" integer NOT NULL DEFAULT 1;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CaseCourtHistory_Cases') THEN
        ALTER TABLE "CaseCourtHistory"
            ADD CONSTRAINT "FK_CaseCourtHistory_Cases"
            FOREIGN KEY ("Case_Id") REFERENCES "Cases"("Code") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CaseCourtHistory_OldCourt') THEN
        ALTER TABLE "CaseCourtHistory"
            ADD CONSTRAINT "FK_CaseCourtHistory_OldCourt"
            FOREIGN KEY ("OldCourt_Id") REFERENCES "Courts"("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_CaseCourtHistory_NewCourt') THEN
        ALTER TABLE "CaseCourtHistory"
            ADD CONSTRAINT "FK_CaseCourtHistory_NewCourt"
            FOREIGN KEY ("NewCourt_Id") REFERENCES "Courts"("Id") ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_CaseCourtHistory_Case_Id_ChangedAt" ON "CaseCourtHistory"("Case_Id", "ChangedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_CaseCourtHistory_FirmId" ON "CaseCourtHistory"("FirmId");
CREATE INDEX IF NOT EXISTS "IX_CaseCourtHistory_OldCourt_Id" ON "CaseCourtHistory"("OldCourt_Id");
CREATE INDEX IF NOT EXISTS "IX_CaseCourtHistory_NewCourt_Id" ON "CaseCourtHistory"("NewCourt_Id");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("Case court history schema ensured");
    }
}
