// <auto-generated />
using System;
using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LawyerSys.Infrastructure.Data.Migrations.Legacy
{
    [DbContext(typeof(LegacyDbContext))]
    [Migration("20260403113411_AddUserProfileImagePath")]
    partial class AddUserProfileImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AdminstrativeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Task_Date")
                        .HasColumnType("date");

                    b.Property<string>("Task_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Task_Reminder_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("employee_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("employee_Id");

                    b.ToTable("AdminstrativeTasks");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Page_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("App_Pages");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Sitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("App_PageID")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsVaild")
                        .HasColumnType("boolean");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("App_PageID");

                    b.HasIndex("User_Id");

                    b.ToTable("App_Sitting", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Pay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("Custmor_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date_Of_Opreation")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Custmor_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Billing_Pay", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date_Of_Opreation")
                        .HasColumnType("date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Billing_Receipt", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Case", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Invition_Date")
                        .HasColumnType("date");

                    b.Property<string>("Invition_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Invitions_Statment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Total_Amount")
                        .HasColumnType("integer");

                    b.HasKey("Code")
                        .HasName("PK_Cases_1");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CaseConversationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AttachmentFileId")
                        .HasColumnType("integer");

                    b.Property<int>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ReadByCustomerAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReadByOfficeAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("VisibleToCustomer")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CaseConversationMessages", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CaseStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CaseStatusHistory", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Contender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Contender_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("Contender_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Contenders");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("Court_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Code");

                    b.HasIndex("Court_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("File_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("File_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Siting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Siting_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Case_Code");

                    b.HasIndex("FirmId");

                    b.HasIndex("Siting_Id");

                    b.ToTable("Cases_Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Con_Lawyers_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Con_Custmor_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Con_Lawyer_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Con_Lawyer_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Con_Lawyers_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consltitions_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Consl_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Consl_Id");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consltitions_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Consultion_State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descraption")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consulations");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulations_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Consl_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consulations_Employee", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SSN")
                        .HasColumnType("integer");

                    b.Property<bool?>("Type")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Con_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Con_Lawyer_ID")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Con_Id");

                    b.HasIndex("Con_Lawyer_ID");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contender_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Contender_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders_Lawyers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Gov_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Gov_Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationDeadlineRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anchor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("integer");

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("PackId");

                    b.ToTable("CourtAutomationDeadlineRules", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationFilingChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("PackId");

                    b.ToTable("CourtAutomationFilingChannels", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationFilingSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int?>("CourtId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FilingChannel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("FormKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastStatusAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("NextCheckAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PackKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("PackKey", "CaseCode");

                    b.ToTable("CourtAutomationFilingSubmissions", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationFormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("PackId");

                    b.ToTable("CourtAutomationFormTemplates", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JurisdictionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Key");

                    b.ToTable("CourtAutomationPacks", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Custmors_Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Custmors_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("Custmors_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Custmors_Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Users_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Users_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CustomerCaseNotificationSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("CaseCode", "CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerCaseNotificationSettings", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CustomerPaymentProof", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int?>("BillingPaymentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("ProofFileId")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CustomerPaymentProofs", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CustomerRequestedDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UploadedFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CustomerRequestedDocuments", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.DocumentDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BrandingJson")
                        .HasColumnType("text");

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<string>("ClauseKeysJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DraftName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FeeTerms")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PartiesJson")
                        .HasColumnType("text");

                    b.Property<string>("PreviewContent")
                        .HasColumnType("text");

                    b.Property<bool>("SaveToCase")
                        .HasColumnType("boolean");

                    b.Property<string>("Scope")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Statement")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseCode");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FirmId");

                    b.ToTable("DocumentDrafts", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.ESignatureRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PublicToken")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SignedByName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SignerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SignerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SignerPhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("TemplateType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("ESignatureRequests", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.Property<int>("Users_Id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Users_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Path")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("type")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.GeneratedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandingJson")
                        .HasColumnType("text");

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<string>("ClauseKeysJson")
                        .HasColumnType("text");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GeneratedContent")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("PartiesJson")
                        .HasColumnType("text");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseCode");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FileId");

                    b.HasIndex("FirmId");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("ParentDocumentId");

                    b.ToTable("GeneratedDocuments", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Governament", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Gov_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Governaments");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.IntakeLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("AssignedEmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConflictChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("ConflictDetails")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("ConvertedCaseCode")
                        .HasColumnType("integer");

                    b.Property<int?>("ConvertedCustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DesiredCaseType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("NextFollowUpAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("QualificationNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("IntakeLeads", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Judicial_Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Customers_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Doc_Num")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Num_Of_Agent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Customers_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Judicial_Documents");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Siting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Judge_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Siting_Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("Siting_Notification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Siting_Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.TimeTrackingEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<decimal?>("SuggestedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("TimeTrackingEntries", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.TrustLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int?>("CaseCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CaseCode");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FirmId");

                    b.ToTable("TrustLedgerEntries", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.TrustReconciliation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("BankStatementBalance")
                        .HasColumnType("double precision");

                    b.Property<double>("BankToBookDifference")
                        .HasColumnType("double precision");

                    b.Property<double>("BookBalance")
                        .HasColumnType("double precision");

                    b.Property<double>("ClientLedgerBalance")
                        .HasColumnType("double precision");

                    b.Property<double>("ClientToBookDifference")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateOnly>("ReconciliationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("TrustReconciliations", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Phon_Number")
                        .HasColumnType("integer");

                    b.Property<string>("Profile_Image_Path")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("SSN")
                        .HasColumnType("integer");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.__EFMigrationsHistory_Legacy", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory_Legacy", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AdminstrativeTask", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "employee")
                        .WithMany("AdminstrativeTasks")
                        .HasForeignKey("employee_Id")
                        .HasConstraintName("FK_AdminstrativeTasks_AdminstrativeTasks");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Sitting", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.App_Page", "App_Page")
                        .WithMany("App_Sittings")
                        .HasForeignKey("App_PageID")
                        .IsRequired()
                        .HasConstraintName("FK_App_Sitting_App_Pages");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "User")
                        .WithMany("App_Sittings")
                        .HasForeignKey("User_Id")
                        .IsRequired()
                        .HasConstraintName("FK_App_Sitting_Users");

                    b.Navigation("App_Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Pay", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Custmor")
                        .WithMany("Billing_Pays")
                        .HasForeignKey("Custmor_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Pay_Customers");

                    b.Navigation("Custmor");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Receipt", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Employee")
                        .WithMany("Billing_Receipts")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Receipt_Customers");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CaseStatusHistory", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("CaseStatusHistories")
                        .HasForeignKey("Case_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CaseStatusHistory_Cases");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Contender", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Cases_Contenders")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Contenders_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Contender")
                        .WithMany("Cases_Contenders")
                        .HasForeignKey("Contender_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Contenders_Contenders");

                    b.Navigation("Case");

                    b.Navigation("Contender");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Court", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case_CodeNavigation")
                        .WithMany("Cases_Courts")
                        .HasForeignKey("Case_Code")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Courts_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Court", "Court")
                        .WithMany("Cases_Courts")
                        .HasForeignKey("Court_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Courts_Courts");

                    b.Navigation("Case_CodeNavigation");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "Employee")
                        .WithMany("Cases_Employees")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Employees_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_File", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Cases_Files")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Files_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.File", "File")
                        .WithMany("Cases_Files")
                        .HasForeignKey("File_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Files_Files");

                    b.Navigation("Case");

                    b.Navigation("File");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Siting", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case_CodeNavigation")
                        .WithMany("Cases_Sitings")
                        .HasForeignKey("Case_Code")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Sitings_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Siting", "Siting")
                        .WithMany("Cases_Sitings")
                        .HasForeignKey("Siting_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Sitings_Sitings");

                    b.Navigation("Case_CodeNavigation");

                    b.Navigation("Siting");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Con_Lawyers_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", "Con_Lawyer")
                        .WithMany("Con_Lawyers_Custmors")
                        .HasForeignKey("Con_Lawyer_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Con_Lawyers_Custmors_Contenders_Lawyers");

                    b.Navigation("Con_Lawyer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consltitions_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Consulation", "Consl")
                        .WithMany("Consltitions_Custmors")
                        .HasForeignKey("Consl_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consltitions_Custmors_Consulations");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customer")
                        .WithMany("Consltitions_Custmors")
                        .HasForeignKey("Customer_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consltitions_Custmors_Customers");

                    b.Navigation("Consl");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulations_Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "Employee")
                        .WithMany("Consulations_Employees")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consulations_Employee_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Con")
                        .WithMany("Contenders_Custmors")
                        .HasForeignKey("Con_Id")
                        .HasConstraintName("FK_Contenders_Custmors_Contenders");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", "Con_Lawyer")
                        .WithMany("Contenders_Custmors")
                        .HasForeignKey("Con_Lawyer_ID")
                        .HasConstraintName("FK_Contenders_Custmors_Contenders_Lawyers");

                    b.Navigation("Con");

                    b.Navigation("Con_Lawyer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Contender")
                        .WithMany("Contenders_Lawyers")
                        .HasForeignKey("Contender_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Contenders_Lawyers_Contenders");

                    b.Navigation("Contender");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Governament", "Gov")
                        .WithMany("Courts")
                        .HasForeignKey("Gov_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Courts_Governaments");

                    b.Navigation("Gov");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationDeadlineRule", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.CourtAutomationPack", "Pack")
                        .WithMany("DeadlineRules")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourtAutomationDeadlineRules_Packs");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationFilingChannel", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.CourtAutomationPack", "Pack")
                        .WithMany("FilingChannels")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourtAutomationFilingChannels_Packs");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationFormTemplate", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.CourtAutomationPack", "Pack")
                        .WithMany("FormTemplates")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourtAutomationFormTemplates_Packs");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Custmors_Case", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Custmors_Cases")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Custmors_Cases_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Custmors")
                        .WithMany("Custmors_Cases")
                        .HasForeignKey("Custmors_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Custmors_Cases_Customers");

                    b.Navigation("Case");

                    b.Navigation("Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Customers")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.DocumentDraft", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_DocumentDrafts_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_DocumentDrafts_Customers");

                    b.Navigation("Case");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Employees")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.GeneratedDocument", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_GeneratedDocuments_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_GeneratedDocuments_Customers");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_GeneratedDocuments_Files");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.GeneratedDocument", "ParentDocument")
                        .WithMany("ChildDocuments")
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_GeneratedDocuments_ParentDocument");

                    b.Navigation("Case");

                    b.Navigation("Customer");

                    b.Navigation("File");

                    b.Navigation("ParentDocument");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Judicial_Document", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customers")
                        .WithMany("Judicial_Documents")
                        .HasForeignKey("Customers_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Judicial_Documents_Customers");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.TrustLedgerEntry", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TrustLedgerEntries_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TrustLedgerEntries_Customers");

                    b.Navigation("Case");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Page", b =>
                {
                    b.Navigation("App_Sittings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Case", b =>
                {
                    b.Navigation("CaseStatusHistories");

                    b.Navigation("Cases_Contenders");

                    b.Navigation("Cases_Courts");

                    b.Navigation("Cases_Files");

                    b.Navigation("Cases_Sitings");

                    b.Navigation("Custmors_Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulation", b =>
                {
                    b.Navigation("Consltitions_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contender", b =>
                {
                    b.Navigation("Cases_Contenders");

                    b.Navigation("Contenders_Custmors");

                    b.Navigation("Contenders_Lawyers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.Navigation("Con_Lawyers_Custmors");

                    b.Navigation("Contenders_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.Navigation("Cases_Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CourtAutomationPack", b =>
                {
                    b.Navigation("DeadlineRules");

                    b.Navigation("FilingChannels");

                    b.Navigation("FormTemplates");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.Navigation("Billing_Pays");

                    b.Navigation("Billing_Receipts");

                    b.Navigation("Consltitions_Custmors");

                    b.Navigation("Custmors_Cases");

                    b.Navigation("Judicial_Documents");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.Navigation("AdminstrativeTasks");

                    b.Navigation("Cases_Employees");

                    b.Navigation("Consulations_Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.File", b =>
                {
                    b.Navigation("Cases_Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.GeneratedDocument", b =>
                {
                    b.Navigation("ChildDocuments");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Governament", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Siting", b =>
                {
                    b.Navigation("Cases_Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Navigation("App_Sittings");

                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
