// <auto-generated />
using System;
using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LawyerSys.Infrastructure.Data.Migrations.Legacy
{
    [DbContext(typeof(LegacyDbContext))]
    partial class LegacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AdminstrativeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Task_Date")
                        .HasColumnType("date");

                    b.Property<string>("Task_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Task_Reminder_Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("employee_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("employee_Id");

                    b.ToTable("AdminstrativeTasks");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Page_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("App_Pages");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Sitting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("App_PageID")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsVaild")
                        .HasColumnType("boolean");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("App_PageID");

                    b.HasIndex("User_Id");

                    b.ToTable("App_Sitting", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Pay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("Custmor_Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date_Of_Opreation")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Custmor_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Billing_Pay", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Date_Of_Opreation")
                        .HasColumnType("date");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Billing_Receipt", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Case", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Invition_Date")
                        .HasColumnType("date");

                    b.Property<string>("Invition_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Invitions_Statment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Total_Amount")
                        .HasColumnType("integer");

                    b.HasKey("Code")
                        .HasName("PK_Cases_1");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CaseStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CaseStatusHistory", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Contender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Contender_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("Contender_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Contenders");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("Court_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Code");

                    b.HasIndex("Court_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("File_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("File_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Cases_Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Siting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Code")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Siting_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Case_Code");

                    b.HasIndex("FirmId");

                    b.HasIndex("Siting_Id");

                    b.ToTable("Cases_Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Con_Lawyers_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Con_Custmor_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Con_Lawyer_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Con_Lawyer_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Con_Lawyers_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consltitions_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Consl_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Consl_Id");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consltitions_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Consultion_State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descraption")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consulations");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulations_Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Consl_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Employee_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Consulations_Employee", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SSN")
                        .HasColumnType("integer");

                    b.Property<bool?>("Type")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Custmor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Con_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Con_Lawyer_ID")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Con_Id");

                    b.HasIndex("Con_Lawyer_ID");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contender_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Contender_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Contenders_Lawyers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Gov_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Gov_Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Custmors_Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Case_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Custmors_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Case_Id");

                    b.HasIndex("Custmors_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Custmors_Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Users_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Users_Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Salary")
                        .HasColumnType("integer");

                    b.Property<int>("Users_Id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("FirmId");

                    b.HasIndex("Users_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Path")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("type")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Governament", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Gov_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Governaments");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Judicial_Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Customers_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Doc_Num")
                        .HasColumnType("integer");

                    b.Property<string>("Doc_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Num_Of_Agent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Customers_Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Judicial_Documents");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Siting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Judge_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Siting_Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("Siting_Notification")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Siting_Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Phon_Number")
                        .HasColumnType("integer");

                    b.Property<int>("SSN")
                        .HasColumnType("integer");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.__EFMigrationsHistory_Legacy", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("MigrationId");

                    b.ToTable("__EFMigrationsHistory_Legacy", (string)null);
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.AdminstrativeTask", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "employee")
                        .WithMany("AdminstrativeTasks")
                        .HasForeignKey("employee_Id")
                        .HasConstraintName("FK_AdminstrativeTasks_AdminstrativeTasks");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Sitting", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.App_Page", "App_Page")
                        .WithMany("App_Sittings")
                        .HasForeignKey("App_PageID")
                        .IsRequired()
                        .HasConstraintName("FK_App_Sitting_App_Pages");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "User")
                        .WithMany("App_Sittings")
                        .HasForeignKey("User_Id")
                        .IsRequired()
                        .HasConstraintName("FK_App_Sitting_Users");

                    b.Navigation("App_Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Pay", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Custmor")
                        .WithMany("Billing_Pays")
                        .HasForeignKey("Custmor_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Pay_Customers");

                    b.Navigation("Custmor");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Billing_Receipt", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Employee")
                        .WithMany("Billing_Receipts")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Billing_Receipt_Customers");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.CaseStatusHistory", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("CaseStatusHistories")
                        .HasForeignKey("Case_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CaseStatusHistory_Cases");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Contender", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Cases_Contenders")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Contenders_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Contender")
                        .WithMany("Cases_Contenders")
                        .HasForeignKey("Contender_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Contenders_Contenders");

                    b.Navigation("Case");

                    b.Navigation("Contender");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Court", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case_CodeNavigation")
                        .WithMany("Cases_Courts")
                        .HasForeignKey("Case_Code")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Courts_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Court", "Court")
                        .WithMany("Cases_Courts")
                        .HasForeignKey("Court_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Courts_Courts");

                    b.Navigation("Case_CodeNavigation");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "Employee")
                        .WithMany("Cases_Employees")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Employees_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_File", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Cases_Files")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Files_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.File", "File")
                        .WithMany("Cases_Files")
                        .HasForeignKey("File_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Files_Files");

                    b.Navigation("Case");

                    b.Navigation("File");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Cases_Siting", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case_CodeNavigation")
                        .WithMany("Cases_Sitings")
                        .HasForeignKey("Case_Code")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Sitings_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Siting", "Siting")
                        .WithMany("Cases_Sitings")
                        .HasForeignKey("Siting_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Cases_Sitings_Sitings");

                    b.Navigation("Case_CodeNavigation");

                    b.Navigation("Siting");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Con_Lawyers_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", "Con_Lawyer")
                        .WithMany("Con_Lawyers_Custmors")
                        .HasForeignKey("Con_Lawyer_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Con_Lawyers_Custmors_Contenders_Lawyers");

                    b.Navigation("Con_Lawyer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consltitions_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Consulation", "Consl")
                        .WithMany("Consltitions_Custmors")
                        .HasForeignKey("Consl_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consltitions_Custmors_Consulations");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customer")
                        .WithMany("Consltitions_Custmors")
                        .HasForeignKey("Customer_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consltitions_Custmors_Customers");

                    b.Navigation("Consl");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulations_Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Employee", "Employee")
                        .WithMany("Consulations_Employees")
                        .HasForeignKey("Employee_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Consulations_Employee_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Custmor", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Con")
                        .WithMany("Contenders_Custmors")
                        .HasForeignKey("Con_Id")
                        .HasConstraintName("FK_Contenders_Custmors_Contenders");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", "Con_Lawyer")
                        .WithMany("Contenders_Custmors")
                        .HasForeignKey("Con_Lawyer_ID")
                        .HasConstraintName("FK_Contenders_Custmors_Contenders_Lawyers");

                    b.Navigation("Con");

                    b.Navigation("Con_Lawyer");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Contender", "Contender")
                        .WithMany("Contenders_Lawyers")
                        .HasForeignKey("Contender_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Contenders_Lawyers_Contenders");

                    b.Navigation("Contender");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Governament", "Gov")
                        .WithMany("Courts")
                        .HasForeignKey("Gov_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Courts_Governaments");

                    b.Navigation("Gov");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Custmors_Case", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Case", "Case")
                        .WithMany("Custmors_Cases")
                        .HasForeignKey("Case_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Custmors_Cases_Cases");

                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Custmors")
                        .WithMany("Custmors_Cases")
                        .HasForeignKey("Custmors_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Custmors_Cases_Customers");

                    b.Navigation("Case");

                    b.Navigation("Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Customers")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Customers_Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.User", "Users")
                        .WithMany("Employees")
                        .HasForeignKey("Users_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Judicial_Document", b =>
                {
                    b.HasOne("LawyerSys.Data.ScaffoldedModels.Customer", "Customers")
                        .WithMany("Judicial_Documents")
                        .HasForeignKey("Customers_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Judicial_Documents_Customers");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.App_Page", b =>
                {
                    b.Navigation("App_Sittings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Case", b =>
                {
                    b.Navigation("CaseStatusHistories");

                    b.Navigation("Cases_Contenders");

                    b.Navigation("Cases_Courts");

                    b.Navigation("Cases_Files");

                    b.Navigation("Cases_Sitings");

                    b.Navigation("Custmors_Cases");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Consulation", b =>
                {
                    b.Navigation("Consltitions_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contender", b =>
                {
                    b.Navigation("Cases_Contenders");

                    b.Navigation("Contenders_Custmors");

                    b.Navigation("Contenders_Lawyers");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Contenders_Lawyer", b =>
                {
                    b.Navigation("Con_Lawyers_Custmors");

                    b.Navigation("Contenders_Custmors");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Court", b =>
                {
                    b.Navigation("Cases_Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Customer", b =>
                {
                    b.Navigation("Billing_Pays");

                    b.Navigation("Billing_Receipts");

                    b.Navigation("Consltitions_Custmors");

                    b.Navigation("Custmors_Cases");

                    b.Navigation("Judicial_Documents");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Employee", b =>
                {
                    b.Navigation("AdminstrativeTasks");

                    b.Navigation("Cases_Employees");

                    b.Navigation("Consulations_Employees");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.File", b =>
                {
                    b.Navigation("Cases_Files");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Governament", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.Siting", b =>
                {
                    b.Navigation("Cases_Sitings");
                });

            modelBuilder.Entity("LawyerSys.Data.ScaffoldedModels.User", b =>
                {
                    b.Navigation("App_Sittings");

                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
