CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "__EFMigrationsHistory_Legacy" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Legacy" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "App_Pages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Page_Name" character varying(50) NOT NULL,
    CONSTRAINT "PK_App_Pages" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EntityName" character varying(128) NOT NULL,
    "Action" character varying(16) NOT NULL,
    "EntityId" character varying(256),
    "OldValues" text,
    "NewValues" text,
    "UserId" character varying(256),
    "UserName" character varying(256),
    "Timestamp" timestamp without time zone NOT NULL,
    "RequestPath" character varying(512),
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Cases" (
    "Code" integer NOT NULL,
    "Id" integer NOT NULL,
    "Invitions_Statment" character varying(50) NOT NULL,
    "Invition_Type" character varying(50) NOT NULL,
    "Invition_Date" date NOT NULL,
    "Total_Amount" integer NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "Status" integer NOT NULL DEFAULT 0,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_1" PRIMARY KEY ("Code")
);

CREATE TABLE "Consulations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Consultion_State" character varying(50) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Subject" character varying(50) NOT NULL,
    "Descraption" character varying(50) NOT NULL,
    "Feedback" character varying(50) NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "Date_time" timestamp without time zone NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Consulations" PRIMARY KEY ("Id")
);

CREATE TABLE "Contenders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Full_Name" character varying(50) NOT NULL,
    "SSN" integer NOT NULL,
    "BirthDate" date NOT NULL,
    "Type" boolean,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Contenders" PRIMARY KEY ("Id")
);

CREATE TABLE "Files" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Path" character varying(50),
    "Code" character varying(50),
    type boolean,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id")
);

CREATE TABLE "Governaments" (
    "Id" integer NOT NULL,
    "Gov_Name" character varying(50) NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Governaments" PRIMARY KEY ("Id")
);

CREATE TABLE "Sitings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Siting_Time" timestamp without time zone NOT NULL,
    "Siting_Date" date NOT NULL,
    "Siting_Notification" timestamp without time zone NOT NULL,
    "Judge_Name" character varying(50) NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Sitings" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL,
    "Full_Name" character varying(50) NOT NULL,
    "Address" character varying(50),
    "Job" character varying(50) NOT NULL,
    "Phon_Number" integer NOT NULL,
    "Date_Of_Birth" date NOT NULL,
    "SSN" integer NOT NULL,
    "User_Name" character varying(50) NOT NULL,
    "Password" character varying(50) NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "CaseStatusHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Id" integer NOT NULL,
    "OldStatus" integer NOT NULL,
    "NewStatus" integer NOT NULL,
    "ChangedBy" text,
    "ChangedAt" timestamp without time zone NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_CaseStatusHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CaseStatusHistory_Cases" FOREIGN KEY ("Case_Id") REFERENCES "Cases" ("Code") ON DELETE CASCADE
);

CREATE TABLE "Cases_Contenders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Id" integer NOT NULL,
    "Contender_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_Contenders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cases_Contenders_Cases" FOREIGN KEY ("Case_Id") REFERENCES "Cases" ("Code"),
    CONSTRAINT "FK_Cases_Contenders_Contenders" FOREIGN KEY ("Contender_Id") REFERENCES "Contenders" ("Id")
);

CREATE TABLE "Contenders_Lawyers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Contender_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Contenders_Lawyers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contenders_Lawyers_Contenders" FOREIGN KEY ("Contender_Id") REFERENCES "Contenders" ("Id")
);

CREATE TABLE "Cases_Files" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Id" integer NOT NULL,
    "File_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cases_Files_Cases" FOREIGN KEY ("Case_Id") REFERENCES "Cases" ("Code"),
    CONSTRAINT "FK_Cases_Files_Files" FOREIGN KEY ("File_Id") REFERENCES "Files" ("Id")
);

CREATE TABLE "Courts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Address" character varying(50) NOT NULL,
    "Telephone" character varying(50) NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "Gov_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Courts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Courts_Governaments" FOREIGN KEY ("Gov_Id") REFERENCES "Governaments" ("Id")
);

CREATE TABLE "Cases_Sitings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Code" integer NOT NULL,
    "Siting_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_Sitings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cases_Sitings_Cases" FOREIGN KEY ("Case_Code") REFERENCES "Cases" ("Code"),
    CONSTRAINT "FK_Cases_Sitings_Sitings" FOREIGN KEY ("Siting_Id") REFERENCES "Sitings" ("Id")
);

CREATE TABLE "App_Sitting" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "User_Id" integer NOT NULL,
    "App_PageID" integer NOT NULL,
    "IsVaild" boolean,
    CONSTRAINT "PK_App_Sitting" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_App_Sitting_App_Pages" FOREIGN KEY ("App_PageID") REFERENCES "App_Pages" ("Id"),
    CONSTRAINT "FK_App_Sitting_Users" FOREIGN KEY ("User_Id") REFERENCES "Users" ("Id")
);

CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Users_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customers_Customers" FOREIGN KEY ("Users_Id") REFERENCES "Users" ("Id")
);

CREATE TABLE "Employees" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "Salary" integer NOT NULL,
    "Users_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Employees" PRIMARY KEY (id),
    CONSTRAINT "FK_Employees_Users" FOREIGN KEY ("Users_Id") REFERENCES "Users" ("Id")
);

CREATE TABLE "Con_Lawyers_Custmors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Con_Custmor_Id" integer NOT NULL,
    "Con_Lawyer_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Con_Lawyers_Custmors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Con_Lawyers_Custmors_Contenders_Lawyers" FOREIGN KEY ("Con_Lawyer_Id") REFERENCES "Contenders_Lawyers" ("Id")
);

CREATE TABLE "Contenders_Custmors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Con_Lawyer_ID" integer,
    "Con_Id" integer,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Contenders_Custmors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contenders_Custmors_Contenders" FOREIGN KEY ("Con_Id") REFERENCES "Contenders" ("Id"),
    CONSTRAINT "FK_Contenders_Custmors_Contenders_Lawyers" FOREIGN KEY ("Con_Lawyer_ID") REFERENCES "Contenders_Lawyers" ("Id")
);

CREATE TABLE "Cases_Courts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Court_Id" integer NOT NULL,
    "Case_Code" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_Courts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cases_Courts_Cases" FOREIGN KEY ("Case_Code") REFERENCES "Cases" ("Code"),
    CONSTRAINT "FK_Cases_Courts_Courts" FOREIGN KEY ("Court_Id") REFERENCES "Courts" ("Id")
);

CREATE TABLE "Billing_Pay" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" double precision NOT NULL,
    "Date_Of_Opreation" date NOT NULL,
    "Notes" text NOT NULL,
    "Custmor_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Billing_Pay" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Billing_Pay_Customers" FOREIGN KEY ("Custmor_Id") REFERENCES "Customers" ("Id")
);

CREATE TABLE "Billing_Receipt" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Amount" double precision NOT NULL,
    "Date_Of_Opreation" date NOT NULL,
    "Notes" text NOT NULL,
    "Employee_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Billing_Receipt" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Billing_Receipt_Customers" FOREIGN KEY ("Employee_Id") REFERENCES "Customers" ("Id")
);

CREATE TABLE "Consltitions_Custmors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Customer_Id" integer NOT NULL,
    "Consl_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Consltitions_Custmors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Consltitions_Custmors_Consulations" FOREIGN KEY ("Consl_Id") REFERENCES "Consulations" ("Id"),
    CONSTRAINT "FK_Consltitions_Custmors_Customers" FOREIGN KEY ("Customer_Id") REFERENCES "Customers" ("Id")
);

CREATE TABLE "Custmors_Cases" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Id" integer NOT NULL,
    "Custmors_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Custmors_Cases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Custmors_Cases_Cases" FOREIGN KEY ("Case_Id") REFERENCES "Cases" ("Code"),
    CONSTRAINT "FK_Custmors_Cases_Customers" FOREIGN KEY ("Custmors_Id") REFERENCES "Customers" ("Id")
);

CREATE TABLE "Judicial_Documents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Doc_Type" character varying(50) NOT NULL,
    "Doc_Num" integer NOT NULL,
    "Doc_Details" character varying(50) NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "Num_Of_Agent" integer NOT NULL,
    "Customers_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Judicial_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Judicial_Documents_Customers" FOREIGN KEY ("Customers_Id") REFERENCES "Customers" ("Id")
);

CREATE TABLE "AdminstrativeTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Task_Name" character varying(50) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Task_Date" date NOT NULL,
    "Task_Reminder_Date" timestamp without time zone NOT NULL,
    "Notes" character varying(50) NOT NULL,
    "employee_Id" integer,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_AdminstrativeTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdminstrativeTasks_AdminstrativeTasks" FOREIGN KEY ("employee_Id") REFERENCES "Employees" (id)
);

CREATE TABLE "Cases_Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Case_Code" integer NOT NULL,
    "Employee_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Cases_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cases_Employees_Employees" FOREIGN KEY ("Employee_Id") REFERENCES "Employees" (id)
);

CREATE TABLE "Consulations_Employee" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Consl_ID" integer NOT NULL,
    "Employee_Id" integer NOT NULL,
    "FirmId" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_Consulations_Employee" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Consulations_Employee_Employees" FOREIGN KEY ("Employee_Id") REFERENCES "Employees" (id)
);

CREATE INDEX "IX_AdminstrativeTasks_employee_Id" ON "AdminstrativeTasks" ("employee_Id");

CREATE INDEX "IX_AdminstrativeTasks_FirmId" ON "AdminstrativeTasks" ("FirmId");

CREATE INDEX "IX_App_Sitting_App_PageID" ON "App_Sitting" ("App_PageID");

CREATE INDEX "IX_App_Sitting_User_Id" ON "App_Sitting" ("User_Id");

CREATE INDEX "IX_AuditLogs_FirmId" ON "AuditLogs" ("FirmId");

CREATE INDEX "IX_Billing_Pay_Custmor_Id" ON "Billing_Pay" ("Custmor_Id");

CREATE INDEX "IX_Billing_Pay_FirmId" ON "Billing_Pay" ("FirmId");

CREATE INDEX "IX_Billing_Receipt_Employee_Id" ON "Billing_Receipt" ("Employee_Id");

CREATE INDEX "IX_Billing_Receipt_FirmId" ON "Billing_Receipt" ("FirmId");

CREATE INDEX "IX_Cases_FirmId" ON "Cases" ("FirmId");

CREATE INDEX "IX_Cases_Contenders_Case_Id" ON "Cases_Contenders" ("Case_Id");

CREATE INDEX "IX_Cases_Contenders_Contender_Id" ON "Cases_Contenders" ("Contender_Id");

CREATE INDEX "IX_Cases_Contenders_FirmId" ON "Cases_Contenders" ("FirmId");

CREATE INDEX "IX_Cases_Courts_Case_Code" ON "Cases_Courts" ("Case_Code");

CREATE INDEX "IX_Cases_Courts_Court_Id" ON "Cases_Courts" ("Court_Id");

CREATE INDEX "IX_Cases_Courts_FirmId" ON "Cases_Courts" ("FirmId");

CREATE INDEX "IX_Cases_Employees_Employee_Id" ON "Cases_Employees" ("Employee_Id");

CREATE INDEX "IX_Cases_Employees_FirmId" ON "Cases_Employees" ("FirmId");

CREATE INDEX "IX_Cases_Files_Case_Id" ON "Cases_Files" ("Case_Id");

CREATE INDEX "IX_Cases_Files_File_Id" ON "Cases_Files" ("File_Id");

CREATE INDEX "IX_Cases_Files_FirmId" ON "Cases_Files" ("FirmId");

CREATE INDEX "IX_Cases_Sitings_Case_Code" ON "Cases_Sitings" ("Case_Code");

CREATE INDEX "IX_Cases_Sitings_FirmId" ON "Cases_Sitings" ("FirmId");

CREATE INDEX "IX_Cases_Sitings_Siting_Id" ON "Cases_Sitings" ("Siting_Id");

CREATE INDEX "IX_CaseStatusHistory_Case_Id" ON "CaseStatusHistory" ("Case_Id");

CREATE INDEX "IX_CaseStatusHistory_FirmId" ON "CaseStatusHistory" ("FirmId");

CREATE INDEX "IX_Con_Lawyers_Custmors_Con_Lawyer_Id" ON "Con_Lawyers_Custmors" ("Con_Lawyer_Id");

CREATE INDEX "IX_Con_Lawyers_Custmors_FirmId" ON "Con_Lawyers_Custmors" ("FirmId");

CREATE INDEX "IX_Consltitions_Custmors_Consl_Id" ON "Consltitions_Custmors" ("Consl_Id");

CREATE INDEX "IX_Consltitions_Custmors_Customer_Id" ON "Consltitions_Custmors" ("Customer_Id");

CREATE INDEX "IX_Consltitions_Custmors_FirmId" ON "Consltitions_Custmors" ("FirmId");

CREATE INDEX "IX_Consulations_FirmId" ON "Consulations" ("FirmId");

CREATE INDEX "IX_Consulations_Employee_Employee_Id" ON "Consulations_Employee" ("Employee_Id");

CREATE INDEX "IX_Consulations_Employee_FirmId" ON "Consulations_Employee" ("FirmId");

CREATE INDEX "IX_Contenders_FirmId" ON "Contenders" ("FirmId");

CREATE INDEX "IX_Contenders_Custmors_Con_Id" ON "Contenders_Custmors" ("Con_Id");

CREATE INDEX "IX_Contenders_Custmors_Con_Lawyer_ID" ON "Contenders_Custmors" ("Con_Lawyer_ID");

CREATE INDEX "IX_Contenders_Custmors_FirmId" ON "Contenders_Custmors" ("FirmId");

CREATE INDEX "IX_Contenders_Lawyers_Contender_Id" ON "Contenders_Lawyers" ("Contender_Id");

CREATE INDEX "IX_Contenders_Lawyers_FirmId" ON "Contenders_Lawyers" ("FirmId");

CREATE INDEX "IX_Courts_FirmId" ON "Courts" ("FirmId");

CREATE INDEX "IX_Courts_Gov_Id" ON "Courts" ("Gov_Id");

CREATE INDEX "IX_Custmors_Cases_Case_Id" ON "Custmors_Cases" ("Case_Id");

CREATE INDEX "IX_Custmors_Cases_Custmors_Id" ON "Custmors_Cases" ("Custmors_Id");

CREATE INDEX "IX_Custmors_Cases_FirmId" ON "Custmors_Cases" ("FirmId");

CREATE INDEX "IX_Customers_FirmId" ON "Customers" ("FirmId");

CREATE INDEX "IX_Customers_Users_Id" ON "Customers" ("Users_Id");

CREATE INDEX "IX_Employees_FirmId" ON "Employees" ("FirmId");

CREATE INDEX "IX_Employees_Users_Id" ON "Employees" ("Users_Id");

CREATE INDEX "IX_Files_FirmId" ON "Files" ("FirmId");

CREATE INDEX "IX_Governaments_FirmId" ON "Governaments" ("FirmId");

CREATE INDEX "IX_Judicial_Documents_Customers_Id" ON "Judicial_Documents" ("Customers_Id");

CREATE INDEX "IX_Judicial_Documents_FirmId" ON "Judicial_Documents" ("FirmId");

CREATE INDEX "IX_Sitings_FirmId" ON "Sitings" ("FirmId");

CREATE INDEX "IX_Users_FirmId" ON "Users" ("FirmId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217123518_InitialLegacyPostgresClean', '8.0.4');

COMMIT;

