using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.Notifications;

public class NotificationPreferencesSchemaInitializer
{
    private readonly ApplicationDbContext _context;

    public NotificationPreferencesSchemaInitializer(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "UserNotificationPreferences"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" VARCHAR(450) NOT NULL,
    "CaseUpdatesEnabled" boolean NOT NULL DEFAULT TRUE,
    "BillingUpdatesEnabled" boolean NOT NULL DEFAULT TRUE,
    "DocumentRequestsEnabled" boolean NOT NULL DEFAULT TRUE,
    "ConversationUpdatesEnabled" boolean NOT NULL DEFAULT TRUE,
    "EmailNotificationsEnabled" boolean NOT NULL DEFAULT FALSE,
    "SmsNotificationsEnabled" boolean NOT NULL DEFAULT FALSE,
    "PreferredLanguage" VARCHAR(12) NOT NULL DEFAULT 'en',
    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "UserId" VARCHAR(450) NOT NULL DEFAULT '';
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "CaseUpdatesEnabled" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "BillingUpdatesEnabled" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "DocumentRequestsEnabled" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "ConversationUpdatesEnabled" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "EmailNotificationsEnabled" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "SmsNotificationsEnabled" boolean NOT NULL DEFAULT FALSE;
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "PreferredLanguage" VARCHAR(12) NOT NULL DEFAULT 'en';
ALTER TABLE "UserNotificationPreferences" ADD COLUMN IF NOT EXISTS "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');

CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserNotificationPreferences_UserId" ON "UserNotificationPreferences"("UserId");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("User notification preference schema ensured");
    }
}
