using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.Notifications;

public class PushTokensSchemaInitializer
{
    private readonly ApplicationDbContext _context;

    public PushTokensSchemaInitializer(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "UserPushTokens"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" VARCHAR(450) NOT NULL,
    "Token" VARCHAR(512) NOT NULL,
    "Platform" VARCHAR(50),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "LastSeenAtUtc" timestamp without time zone
);

ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "UserId" VARCHAR(450) NOT NULL DEFAULT '';
ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "Token" VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "Platform" VARCHAR(50);
ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT TRUE;
ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "UserPushTokens" ADD COLUMN IF NOT EXISTS "LastSeenAtUtc" timestamp without time zone;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserPushTokens_UserId_Token" ON "UserPushTokens"("UserId", "Token");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("User push tokens schema ensured");
    }
}
