using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.TimeTracking;

public class TimeTrackingSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public TimeTrackingSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "TimeTrackingEntries"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseCode" integer NULL,
    "CustomerId" integer NULL,
    "WorkType" VARCHAR(64) NOT NULL DEFAULT 'General',
    "Description" VARCHAR(2000) NULL,
    "Status" VARCHAR(24) NOT NULL DEFAULT 'Running',
    "StartedBy" VARCHAR(256) NOT NULL,
    "StartedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "EndedAt" timestamp without time zone NULL,
    "DurationMinutes" integer NOT NULL DEFAULT 0,
    "SuggestedAmount" numeric(18,2) NULL,
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "CaseCode" integer NULL;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "CustomerId" integer NULL;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "WorkType" VARCHAR(64) NOT NULL DEFAULT 'General';
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "Description" VARCHAR(2000) NULL;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "Status" VARCHAR(24) NOT NULL DEFAULT 'Running';
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "StartedBy" VARCHAR(256) NOT NULL DEFAULT 'System';
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "StartedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "EndedAt" timestamp without time zone NULL;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "DurationMinutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "SuggestedAmount" numeric(18,2) NULL;
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "TimeTrackingEntries" ADD COLUMN IF NOT EXISTS "FirmId" integer NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS "IX_TimeTrackingEntries_Status_StartedAt" ON "TimeTrackingEntries"("Status", "StartedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_TimeTrackingEntries_CaseCode" ON "TimeTrackingEntries"("CaseCode");
CREATE INDEX IF NOT EXISTS "IX_TimeTrackingEntries_CustomerId" ON "TimeTrackingEntries"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_TimeTrackingEntries_FirmId" ON "TimeTrackingEntries"("FirmId");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("Time tracking schema ensured");
    }
}
