using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.CustomerExperience;

public class CustomerExperienceSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public CustomerExperienceSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "CustomerRequestedDocuments"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseCode" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "Title" VARCHAR(200) NOT NULL DEFAULT '',
    "Description" VARCHAR(2000) NOT NULL DEFAULT '',
    "DueDate" date NULL,
    "Status" VARCHAR(32) NOT NULL DEFAULT 'Pending',
    "RequestedByUserId" VARCHAR(256) NOT NULL DEFAULT '',
    "RequestedByName" VARCHAR(256) NOT NULL DEFAULT '',
    "CustomerNotes" VARCHAR(2000) NOT NULL DEFAULT '',
    "ReviewNotes" VARCHAR(2000) NOT NULL DEFAULT '',
    "UploadedFileId" integer NULL,
    "RequestedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "SubmittedAtUtc" timestamp without time zone NULL,
    "ReviewedAtUtc" timestamp without time zone NULL,
    "FirmId" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "CustomerPaymentProofs"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" integer NOT NULL,
    "CaseCode" integer NULL,
    "Amount" double precision NOT NULL DEFAULT 0,
    "PaymentDate" date NOT NULL DEFAULT CURRENT_DATE,
    "Notes" VARCHAR(2000) NOT NULL DEFAULT '',
    "ProofFileId" integer NULL,
    "Status" VARCHAR(32) NOT NULL DEFAULT 'Pending',
    "BillingPaymentId" integer NULL,
    "ReviewedByUserId" VARCHAR(256) NOT NULL DEFAULT '',
    "ReviewedByName" VARCHAR(256) NOT NULL DEFAULT '',
    "ReviewNotes" VARCHAR(2000) NOT NULL DEFAULT '',
    "SubmittedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "ReviewedAtUtc" timestamp without time zone NULL,
    "FirmId" integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "CustomerCaseNotificationSettings"
(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseCode" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "NotificationsEnabled" boolean NOT NULL DEFAULT TRUE,
    "UpdatedAtUtc" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "AttachmentFileId" integer NULL;
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "ReadByCustomerAtUtc" timestamp without time zone NULL;
ALTER TABLE "CaseConversationMessages" ADD COLUMN IF NOT EXISTS "ReadByOfficeAtUtc" timestamp without time zone NULL;

CREATE INDEX IF NOT EXISTS "IX_CustomerRequestedDocuments_CaseCode_Status" ON "CustomerRequestedDocuments"("CaseCode", "Status");
CREATE INDEX IF NOT EXISTS "IX_CustomerRequestedDocuments_CustomerId" ON "CustomerRequestedDocuments"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_CustomerRequestedDocuments_FirmId" ON "CustomerRequestedDocuments"("FirmId");

CREATE INDEX IF NOT EXISTS "IX_CustomerPaymentProofs_CustomerId_Status" ON "CustomerPaymentProofs"("CustomerId", "Status");
CREATE INDEX IF NOT EXISTS "IX_CustomerPaymentProofs_CaseCode" ON "CustomerPaymentProofs"("CaseCode");
CREATE INDEX IF NOT EXISTS "IX_CustomerPaymentProofs_FirmId" ON "CustomerPaymentProofs"("FirmId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerCaseNotificationSettings_CaseCode_CustomerId" ON "CustomerCaseNotificationSettings"("CaseCode", "CustomerId");
CREATE INDEX IF NOT EXISTS "IX_CustomerCaseNotificationSettings_FirmId" ON "CustomerCaseNotificationSettings"("FirmId");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("Customer experience schema ensured");
    }
}
