using LawyerSys.Data.ScaffoldedModels;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LawyerSys.Services.Pdf;

public static class ReceiptPdfBuilder
{
    public static byte[] BuildCustomerReceipt(
        string officeName,
        string officePhone,
        string customerName,
        int receiptNumber,
        DateOnly paymentDate,
        double amount,
        string notes,
        int? caseCode)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(32);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(text => text.FontFamily(Fonts.Calibri).FontSize(11));

                page.Header().Column(column =>
                {
                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(left =>
                        {
                            left.Item().Text(officeName).FontSize(24).SemiBold().FontColor("#14345A");
                            left.Item().Text("Payment Receipt").FontSize(12).FontColor("#5C6B7A");
                        });

                        row.ConstantItem(150).AlignRight().Column(right =>
                        {
                            right.Item().Text($"Receipt #{receiptNumber}").SemiBold().FontSize(16);
                            right.Item().Text($"Issued {DateTime.UtcNow:yyyy-MM-dd}");
                            right.Item().Text(string.IsNullOrWhiteSpace(officePhone) ? "-" : officePhone);
                        });
                    });

                    column.Item().PaddingTop(18).LineHorizontal(1).LineColor("#D6DEE6");
                });

                page.Content().PaddingVertical(18).Column(column =>
                {
                    column.Spacing(14);

                    column.Item().Background("#F6F9FC").Border(1).BorderColor("#D6DEE6").Padding(16).Column(summary =>
                    {
                        summary.Spacing(8);
                        summary.Item().Text("Receipt Summary").SemiBold().FontSize(14).FontColor("#14345A");
                        summary.Item().Row(row =>
                        {
                            row.RelativeItem().Column(details =>
                            {
                                details.Spacing(5);
                                details.Item().Text($"Client: {customerName}");
                                details.Item().Text($"Payment date: {paymentDate:yyyy-MM-dd}");
                                details.Item().Text(caseCode.HasValue ? $"Case: #{caseCode.Value}" : "Case: General account payment");
                            });

                            row.ConstantItem(160).AlignRight().Column(amountBlock =>
                            {
                                amountBlock.Spacing(4);
                                amountBlock.Item().Text("Amount received").FontColor("#5C6B7A");
                                amountBlock.Item().Text($"{amount:F2}").FontSize(26).SemiBold().FontColor("#14345A");
                            });
                        });
                    });

                    column.Item().Column(notesBlock =>
                    {
                        notesBlock.Spacing(6);
                        notesBlock.Item().Text("Office Note").SemiBold().FontSize(13).FontColor("#14345A");
                        notesBlock.Item().Border(1).BorderColor("#D6DEE6").Padding(12).Text(string.IsNullOrWhiteSpace(notes) ? "No additional notes." : notes);
                    });

                    column.Item().Background("#14345A").Padding(16).Column(footer =>
                    {
                        footer.Spacing(6);
                        footer.Item().Text("Thank you for working with our office.").FontColor(Colors.White).SemiBold();
                        footer.Item().Text("This receipt confirms that the payment record was created in the system.").FontColor("#D9E8F2");
                    });
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Qadaya").FontColor("#5C6B7A");
                });
            });
        }).GeneratePdf();
    }
}
