using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace LawyerSys.Services.Reminders;

public sealed class ReminderDispatchStore
{
    private readonly SemaphoreSlim _schemaLock = new(1, 1);
    private volatile bool _schemaReady;

    public async Task EnsureSchemaAsync(LegacyDbContext db, CancellationToken cancellationToken = default)
    {
        if (_schemaReady)
            return;

        await _schemaLock.WaitAsync(cancellationToken);
        try
        {
            if (_schemaReady)
                return;

            var sql = @"
CREATE TABLE IF NOT EXISTS ReminderDispatches
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ReminderType VARCHAR(50) NOT NULL,
    ReminderKey VARCHAR(200) NOT NULL,
    Recipient VARCHAR(320) NOT NULL,
    Subject VARCHAR(200) NOT NULL,
    Status VARCHAR(20) NOT NULL,
    ErrorMessage TEXT NULL,
    AttemptedAt TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    SentAt TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS IX_ReminderDispatches_Lookup
    ON ReminderDispatches(ReminderType, ReminderKey, Recipient, Status, AttemptedAt);";

            await db.Database.ExecuteSqlRawAsync(sql, cancellationToken);
            _schemaReady = true;
        }
        finally
        {
            _schemaLock.Release();
        }
    }

    public async Task<bool> HasSuccessfulDispatchAsync(
        LegacyDbContext db,
        string reminderType,
        string reminderKey,
        string recipient,
        CancellationToken cancellationToken = default)
    {
        var cmd = db.Database.GetDbConnection().CreateCommand();
        cmd.CommandText = @"SELECT 1 FROM ReminderDispatches 
                    WHERE ReminderType=@type AND ReminderKey=@key AND Recipient=@recipient AND Status='Sent'
                    LIMIT 1";
        AddParameter(cmd, "@type", reminderType);
        AddParameter(cmd, "@key", reminderKey);
        AddParameter(cmd, "@recipient", recipient);

        if (cmd.Connection!.State != ConnectionState.Open)
            await cmd.Connection.OpenAsync(cancellationToken);

        var result = await cmd.ExecuteScalarAsync(cancellationToken);
        return result != null && result != DBNull.Value;
    }

    public async Task<int> GetAttemptCountAsync(
        LegacyDbContext db,
        string reminderType,
        string reminderKey,
        string recipient,
        CancellationToken cancellationToken = default)
    {
        var cmd = db.Database.GetDbConnection().CreateCommand();
        cmd.CommandText = @"SELECT COUNT(1) FROM ReminderDispatches 
                            WHERE ReminderType=@type AND ReminderKey=@key AND Recipient=@recipient";
        AddParameter(cmd, "@type", reminderType);
        AddParameter(cmd, "@key", reminderKey);
        AddParameter(cmd, "@recipient", recipient);

        if (cmd.Connection!.State != ConnectionState.Open)
            await cmd.Connection.OpenAsync(cancellationToken);

        var result = await cmd.ExecuteScalarAsync(cancellationToken);
        return Convert.ToInt32(result ?? 0);
    }

    public async Task RecordAttemptAsync(
        LegacyDbContext db,
        string reminderType,
        string reminderKey,
        string recipient,
        string subject,
        string status,
        string? errorMessage,
        CancellationToken cancellationToken = default)
    {
        var cmd = db.Database.GetDbConnection().CreateCommand();
        cmd.CommandText = @"INSERT INTO ReminderDispatches
                            (ReminderType, ReminderKey, Recipient, Subject, Status, ErrorMessage, AttemptedAt, SentAt)
                    VALUES (@type, @key, @recipient, @subject, @status, @error, (NOW() AT TIME ZONE 'UTC'),
                        CASE WHEN @status='Sent' THEN (NOW() AT TIME ZONE 'UTC') ELSE NULL END)";
        AddParameter(cmd, "@type", reminderType);
        AddParameter(cmd, "@key", reminderKey);
        AddParameter(cmd, "@recipient", recipient);
        AddParameter(cmd, "@subject", subject);
        AddParameter(cmd, "@status", status);
        AddParameter(cmd, "@error", (object?)errorMessage ?? DBNull.Value);

        if (cmd.Connection!.State != ConnectionState.Open)
            await cmd.Connection.OpenAsync(cancellationToken);

        await cmd.ExecuteNonQueryAsync(cancellationToken);
    }

    private static void AddParameter(IDbCommand command, string name, object? value)
    {
        var p = command.CreateParameter();
        p.ParameterName = name;
        p.Value = value ?? DBNull.Value;
        command.Parameters.Add(p);
    }
}
