using LawyerSys.Data;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace LawyerSys.Services.ESign;

public class ESignSchemaInitializer
{
    private readonly LegacyDbContext _context;

    public ESignSchemaInitializer(LegacyDbContext context)
    {
        _context = context;
    }

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        const string sql = """
CREATE TABLE IF NOT EXISTS "ESignatureRequests"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileId" integer NULL,
    "RequestTitle" VARCHAR(200) NOT NULL,
    "TemplateType" VARCHAR(80) NULL,
    "SignerName" VARCHAR(120) NOT NULL,
    "SignerEmail" VARCHAR(256) NOT NULL,
    "SignerPhoneNumber" VARCHAR(32) NULL,
    "Message" VARCHAR(2000) NULL,
    "CaseCode" integer NULL,
    "CustomerId" integer NULL,
    "Status" VARCHAR(24) NOT NULL DEFAULT 'Pending',
    "ExternalReference" VARCHAR(200) NULL,
    "PublicToken" VARCHAR(120) NULL,
    "TokenExpiresAt" timestamp without time zone NULL,
    "SignedByName" VARCHAR(120) NULL,
    "RequestedBy" VARCHAR(256) NOT NULL,
    "RequestedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "SignedAt" timestamp without time zone NULL,
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    "FirmId" integer NOT NULL DEFAULT 1
);

ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "FileId" integer NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "RequestTitle" VARCHAR(200) NOT NULL DEFAULT 'Untitled Request';
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "TemplateType" VARCHAR(80) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "SignerName" VARCHAR(120) NOT NULL DEFAULT 'Unknown Signer';
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "SignerEmail" VARCHAR(256) NOT NULL DEFAULT 'unknown@example.com';
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "SignerPhoneNumber" VARCHAR(32) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "Message" VARCHAR(2000) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "CaseCode" integer NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "CustomerId" integer NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "Status" VARCHAR(24) NOT NULL DEFAULT 'Pending';
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "ExternalReference" VARCHAR(200) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "PublicToken" VARCHAR(120) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "TokenExpiresAt" timestamp without time zone NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "SignedByName" VARCHAR(120) NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "RequestedBy" VARCHAR(256) NOT NULL DEFAULT 'System';
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "RequestedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "SignedAt" timestamp without time zone NULL;
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC');
ALTER TABLE "ESignatureRequests" ADD COLUMN IF NOT EXISTS "FirmId" integer NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS "IX_ESignatureRequests_Status_RequestedAt" ON "ESignatureRequests"("Status", "RequestedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_ESignatureRequests_SignerEmail" ON "ESignatureRequests"("SignerEmail");
CREATE INDEX IF NOT EXISTS "IX_ESignatureRequests_FileId" ON "ESignatureRequests"("FileId");
CREATE INDEX IF NOT EXISTS "IX_ESignatureRequests_FirmId" ON "ESignatureRequests"("FirmId");
CREATE INDEX IF NOT EXISTS "IX_ESignatureRequests_PublicToken" ON "ESignatureRequests"("PublicToken");
""";

        await _context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        Log.Information("eSignature schema ensured");
    }
}
